/*
	This File Contains all the Pokemon Information
	Kanto Pokedex
	   ...    151
	Bulbasaur		Mew

*/

#define NUM_ALL_POKEMON 151

static char * poke_names[] = {
"Unknown",
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran F",
"Nidorina",
"Nidoqueen",
"Nidoran M",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch'd",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"MissingNo",
NULL};

// TODO: replace [0] with placeholder?
static uint8_t poke_images[] = { \
RESOURCE_ID_IMAGE_poke137,\
RESOURCE_ID_IMAGE_poke1,\
RESOURCE_ID_IMAGE_poke2,\
RESOURCE_ID_IMAGE_poke3,\
RESOURCE_ID_IMAGE_poke4,\
RESOURCE_ID_IMAGE_poke5,\
RESOURCE_ID_IMAGE_poke6,\
RESOURCE_ID_IMAGE_poke7,\
RESOURCE_ID_IMAGE_poke8,\
RESOURCE_ID_IMAGE_poke9,\
RESOURCE_ID_IMAGE_poke10,\
RESOURCE_ID_IMAGE_poke11,\
RESOURCE_ID_IMAGE_poke12,\
RESOURCE_ID_IMAGE_poke13,\
RESOURCE_ID_IMAGE_poke14,\
RESOURCE_ID_IMAGE_poke15,\
RESOURCE_ID_IMAGE_poke16,\
RESOURCE_ID_IMAGE_poke17,\
RESOURCE_ID_IMAGE_poke18,\
RESOURCE_ID_IMAGE_poke19,\
RESOURCE_ID_IMAGE_poke20,\
RESOURCE_ID_IMAGE_poke21,\
RESOURCE_ID_IMAGE_poke22,\
RESOURCE_ID_IMAGE_poke23,\
RESOURCE_ID_IMAGE_poke24,\
RESOURCE_ID_IMAGE_poke25,\
RESOURCE_ID_IMAGE_poke26,\
RESOURCE_ID_IMAGE_poke27,\
RESOURCE_ID_IMAGE_poke28,\
RESOURCE_ID_IMAGE_poke29,\
RESOURCE_ID_IMAGE_poke30,\
RESOURCE_ID_IMAGE_poke31,\
RESOURCE_ID_IMAGE_poke32,\
RESOURCE_ID_IMAGE_poke33,\
RESOURCE_ID_IMAGE_poke34,\
RESOURCE_ID_IMAGE_poke35,\
RESOURCE_ID_IMAGE_poke36,\
RESOURCE_ID_IMAGE_poke37,\
RESOURCE_ID_IMAGE_poke38,\
RESOURCE_ID_IMAGE_poke39,\
RESOURCE_ID_IMAGE_poke40,\
RESOURCE_ID_IMAGE_poke41,\
RESOURCE_ID_IMAGE_poke42,\
RESOURCE_ID_IMAGE_poke43,\
RESOURCE_ID_IMAGE_poke44,\
RESOURCE_ID_IMAGE_poke45,\
RESOURCE_ID_IMAGE_poke46,\
RESOURCE_ID_IMAGE_poke47,\
RESOURCE_ID_IMAGE_poke48,\
RESOURCE_ID_IMAGE_poke49,\
RESOURCE_ID_IMAGE_poke50,\
RESOURCE_ID_IMAGE_poke51,\
RESOURCE_ID_IMAGE_poke52,\
RESOURCE_ID_IMAGE_poke53,\
RESOURCE_ID_IMAGE_poke54,\
RESOURCE_ID_IMAGE_poke55,\
RESOURCE_ID_IMAGE_poke56,\
RESOURCE_ID_IMAGE_poke57,\
RESOURCE_ID_IMAGE_poke58,\
RESOURCE_ID_IMAGE_poke59,\
RESOURCE_ID_IMAGE_poke60,\
RESOURCE_ID_IMAGE_poke61,\
RESOURCE_ID_IMAGE_poke62,\
RESOURCE_ID_IMAGE_poke63,\
RESOURCE_ID_IMAGE_poke64,\
RESOURCE_ID_IMAGE_poke65,\
RESOURCE_ID_IMAGE_poke66,\
RESOURCE_ID_IMAGE_poke67,\
RESOURCE_ID_IMAGE_poke68,\
RESOURCE_ID_IMAGE_poke69,\
RESOURCE_ID_IMAGE_poke70,\
RESOURCE_ID_IMAGE_poke71,\
RESOURCE_ID_IMAGE_poke72,\
RESOURCE_ID_IMAGE_poke73,\
RESOURCE_ID_IMAGE_poke74,\
RESOURCE_ID_IMAGE_poke75,\
RESOURCE_ID_IMAGE_poke76,\
RESOURCE_ID_IMAGE_poke77,\
RESOURCE_ID_IMAGE_poke78,\
RESOURCE_ID_IMAGE_poke79,\
RESOURCE_ID_IMAGE_poke80,\
RESOURCE_ID_IMAGE_poke81,\
RESOURCE_ID_IMAGE_poke82,\
RESOURCE_ID_IMAGE_poke83,\
RESOURCE_ID_IMAGE_poke84,\
RESOURCE_ID_IMAGE_poke85,\
RESOURCE_ID_IMAGE_poke86,\
RESOURCE_ID_IMAGE_poke87,\
RESOURCE_ID_IMAGE_poke88,\
RESOURCE_ID_IMAGE_poke89,\
RESOURCE_ID_IMAGE_poke90,\
RESOURCE_ID_IMAGE_poke91,\
RESOURCE_ID_IMAGE_poke92,\
RESOURCE_ID_IMAGE_poke93,\
RESOURCE_ID_IMAGE_poke94,\
RESOURCE_ID_IMAGE_poke95,\
RESOURCE_ID_IMAGE_poke96,\
RESOURCE_ID_IMAGE_poke97,\
RESOURCE_ID_IMAGE_poke98,\
RESOURCE_ID_IMAGE_poke99,\
RESOURCE_ID_IMAGE_poke100,\
RESOURCE_ID_IMAGE_poke101,\
RESOURCE_ID_IMAGE_poke102,\
RESOURCE_ID_IMAGE_poke103,
RESOURCE_ID_IMAGE_poke104,
RESOURCE_ID_IMAGE_poke105,
RESOURCE_ID_IMAGE_poke106,
RESOURCE_ID_IMAGE_poke107,
RESOURCE_ID_IMAGE_poke108,
RESOURCE_ID_IMAGE_poke109,
RESOURCE_ID_IMAGE_poke110,
RESOURCE_ID_IMAGE_poke111,
RESOURCE_ID_IMAGE_poke112,
RESOURCE_ID_IMAGE_poke113,
RESOURCE_ID_IMAGE_poke114,
RESOURCE_ID_IMAGE_poke115,
RESOURCE_ID_IMAGE_poke116,
RESOURCE_ID_IMAGE_poke117,
RESOURCE_ID_IMAGE_poke118,
RESOURCE_ID_IMAGE_poke119,
RESOURCE_ID_IMAGE_poke120,
RESOURCE_ID_IMAGE_poke121,
RESOURCE_ID_IMAGE_poke122,
RESOURCE_ID_IMAGE_poke123,
RESOURCE_ID_IMAGE_poke124,
RESOURCE_ID_IMAGE_poke125,
RESOURCE_ID_IMAGE_poke126,
RESOURCE_ID_IMAGE_poke127,
RESOURCE_ID_IMAGE_poke128,
RESOURCE_ID_IMAGE_poke129,
RESOURCE_ID_IMAGE_poke130,
RESOURCE_ID_IMAGE_poke131,
RESOURCE_ID_IMAGE_poke132,
RESOURCE_ID_IMAGE_poke133,
RESOURCE_ID_IMAGE_poke134,
RESOURCE_ID_IMAGE_poke135,
RESOURCE_ID_IMAGE_poke136,
RESOURCE_ID_IMAGE_poke137,
RESOURCE_ID_IMAGE_poke138,
RESOURCE_ID_IMAGE_poke139,
RESOURCE_ID_IMAGE_poke140,
RESOURCE_ID_IMAGE_poke141,
RESOURCE_ID_IMAGE_poke142,
RESOURCE_ID_IMAGE_poke143,
RESOURCE_ID_IMAGE_poke144,
RESOURCE_ID_IMAGE_poke145,
RESOURCE_ID_IMAGE_poke146,
RESOURCE_ID_IMAGE_poke147,
RESOURCE_ID_IMAGE_poke148,
RESOURCE_ID_IMAGE_poke149,
RESOURCE_ID_IMAGE_poke150,
RESOURCE_ID_IMAGE_poke151
};
